In [1]:
import cv2
import numpy as np

In [23]:
image = cv2.imread('doc2.jpg')
image = cv2.resize(image, None, fx = .8, fy = .8)
medianBlue = cv2.medianBlur(image, 5)
imageGrey = cv2.cvtColor(medianBlue, cv2.COLOR_BGR2GRAY)
# bilateral = cv2.bilateralFilter(imageGrey, 5, 6,6)
# gaussianBlur = cv2.GaussianBlur(imageGrey, (5,5), 0)

In [25]:
selected_contour = None
image_copy = None

In [4]:
def lowerThresh(lThresh):
    pass

def higherThresh(hThresh):
    pass

In [5]:
def mouseClick(event, x,y, flag, params):
    global selected_contour, image_copy
    if event == cv2.EVENT_LBUTTONDOWN:
        for contour in contours:
            res = cv2.pointPolygonTest(contour, (x,y), False)
            if res>=0:
                selected_contour = contour
                print(f'{contour} Selected')
                break

    copy = image.copy()

    if selected_contour is not None:
        cv2.drawContours(copy, selected_contour, -1, (0,255,0), 2)

    cv2.imshow("contour", copy)

In [41]:
cv2.namedWindow("TrackBar")
cv2.createTrackbar("lThresh", "TrackBar", 35, 255, lowerThresh)
cv2.createTrackbar("hThresh", "TrackBar", 137, 255, higherThresh)

while True:
    lthresh = cv2.getTrackbarPos("lThresh", "TrackBar")
    hthresh = cv2.getTrackbarPos("hThresh", "TrackBar")
    
    # _ , mask1 = cv2.threshold(medianBlue, 210, 255, cv2.THRESH_BINARY)

    edge = cv2.Canny(medianBlue, lthresh, hthresh)
    
    cv2.imshow('image', image)
    cv2.imshow('medianBlue', medianBlue)
    # cv2.imshow('bilateral', bilateral)
    # cv2.imshow('gaussianBlur', gaussianBlur)

    cv2.imshow('edge', edge)
    
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
cv2.destroyAllWindows()


In [44]:
cv2.imshow('edge', edge)
contours, _ = cv2.findContours(edge, mode = cv2.RETR_EXTERNAL, method = cv2.CHAIN_APPROX_SIMPLE)
cv2.setMouseCallback("edge", mouseClick)
while True:
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()

[[[293  77]]

 [[300  77]]

 [[301  78]]

 [[308  78]]

 [[309  79]]

 [[318  79]]

 [[319  80]]

 [[342  80]]

 [[343  81]]

 [[360  81]]

 [[361  82]]

 [[374  82]]

 [[375  83]]

 [[386  83]]

 [[387  84]]

 [[401  84]]

 [[402  85]]

 [[431  85]]

 [[432  86]]

 [[449  86]]

 [[450  87]]

 [[464  87]]

 [[465  88]]

 [[479  88]]

 [[480  89]]

 [[512  89]]

 [[513  90]]

 [[534  90]]

 [[535  91]]

 [[551  91]]

 [[552  92]]

 [[568  92]]

 [[569  93]]

 [[583  93]]

 [[584  92]]

 [[598  92]]

 [[601  95]]

 [[601 366]]

 [[602 367]]

 [[602 457]]

 [[603 458]]

 [[603 507]]

 [[604 508]]

 [[604 548]]

 [[601 551]]

 [[599 551]]

 [[598 550]]

 [[591 550]]

 [[590 549]]

 [[582 549]]

 [[581 548]]

 [[575 548]]

 [[574 547]]

 [[567 547]]

 [[566 546]]

 [[559 546]]

 [[558 545]]

 [[551 545]]

 [[550 544]]

 [[544 544]]

 [[543 543]]

 [[537 543]]

 [[536 542]]

 [[529 542]]

 [[528 541]]

 [[521 541]]

 [[520 540]]

 [[514 540]]

 [[513 539]]

 [[507 539]]

 [[506 538]]

 [[499