In [1]:
import numpy as np

# Matrix Dimention and Orientation

## 1D Arrays

In [48]:
# Row Vector
arr = np.array([1,2,3,4,5])
print(arr)
# Column Vector (has to be a matrix with atleast 2 dimentions)
arr_v = np.array([[1],[2],[3],[4],[5]])
print(arr_v)

# finding the dimention of the vector is
print(f"Diemention of arr  - {arr.ndim}")
print(f"Diemention of arr_v - {arr_v.ndim}")

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
Diemention of arr  - 1
Diemention of arr_v - 2


# N Dimention Arrays

In [67]:
arr_3D = np.array([[[1,2,3,4,5,6], [6,7,8,9,0,12]]])
print(arr_3D)
print(arr_3D.ndim)

[[[ 1  2  3  4  5  6]
  [ 6  7  8  9  0 12]]]
3


# # Fill array of N dimentions with 0

In [95]:
# Creating zero Array
zero_arr = np.zeros((4,5)) # by default created the array of type float
print(zero_arr)

# for creating and integer zero array
zero_arr_i = np.zeros((4,5), dtype = 'int8')
print(zero_arr_i)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# Fill array of N dimentions with 1

In [93]:
# Creating ones Array
one_arr = np.ones((4,5)) # by default created the array of type float
print(one_arr)

# for creating and integer zero array
one_arr_i = np.ones((4,5), dtype = 'int8')
print(one_arr_i)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# Fill array of N dimentions with a custom Value

In [109]:
cus_arr = np.full((2,3), 5) # automatically takes the data type of the value
print(cus_arr)

[[5 5 5]
 [5 5 5]]


# Creating identity matrix

In [114]:
eye_arr = np.eye(5, dtype = 'int8')
print(eye_arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# Auto creating Array

In [122]:
a_arr = np.arange(0,14,3, dtype = 'int8')
print(a_arr)

[ 0  3  6  9 12]


# Creating array with N values with N distance

In [131]:
l_arr = np.linspace(0,5,11)
print(l_arr)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


# Creating NDimentionala array of random numbers

In [143]:
# creating random array of random values
rand_arr = np.random.rand(4,2) #prints random value between 0 & 1, multiply by and integer to get a range
print(rand_arr)
rand_arr_i = np.random.randint(255, size=(4,9))
print(rand_arr_i)

[[0.62552128 0.6651313 ]
 [0.5583523  0.5467591 ]
 [0.15279191 0.98710163]
 [0.35133158 0.78510449]]
[[104  80  28 135  92 229 144  75  53]
 [ 28 107 157 196 175 126 163  26 174]
 [251   2 199 231 199 179 106  27  57]
 [111  87 212  50  81  16 251 225 146]]


# Other Operations

In [157]:
# To fide the shape of the array
print(rand_arr_i.shape)
# To fide the size of the array
print(rand_arr.size)
# to find and chage datatype of the array
print(rand_arr_i.dtype, rand_arr.dtype)
rand_arr_change = rand_arr.astype(int)
print(rand_arr_change.dtype

(4, 9)
8
int32 float64


# Min and Max in a Array

In [160]:
print(rand_arr_i.min(), rand_arr_i.max())

2 251
