In [355]:
!pip install opencv-python

ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install


  Using cached opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl.metadata (20 kB)
Using cached opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl (39.5 MB)


In [1]:
import numpy as np
import cv2

# Indexing in Numpy

In [258]:
# 4D array
arr = np.array([
    [[[1,2,3,4], [4,5,6,7],[7,8,9,0]]], 
    [[[11,12,13,14], [14,15,16,17],[17,18,19,10]]], 
    [ [ [21,22,23,24], [24,25,26,27],[27,28,29,20] ] ]
] )
print(arr)

[[[[ 1  2  3  4]
   [ 4  5  6  7]
   [ 7  8  9  0]]]


 [[[11 12 13 14]
   [14 15 16 17]
   [17 18 19 10]]]


 [[[21 22 23 24]
   [24 25 26 27]
   [27 28 29 20]]]]


In [282]:
 #1stD,2ndD,3rdD,4thD
#  2    0    2   1:3
# 1st Dimension has 3 elements
'''[

   [[[ 1  2  3  4]
   [ 4  5  6  7]
   [ 7  8  9  0]]]


 [[[11 12 13 14]
   [14 15 16 17]
   [17 18 19 10]]]


 [[[21 22 23 24]
   [24 25 26 27]
   [27 28 29 20]]]
   
]'''
# 2st Dimension has 1 elements each
'''[[
   [[ 1  2  3  4]
   [ 4  5  6  7]
   [ 7  8  9  0]]
   ]


 [
 [[11 12 13 14]
   [14 15 16 17]
   [17 18 19 10]]
 ]


 [
 [[21 22 23 24]
   [24 25 26 27]
   [27 28 29 20]]
]
]'''

# 3rd Dimension has 3 elements each
'''
   [ 1  2  3  4]
   [ 4  5  6  7]
   [ 7  8  9  0]
'''
# 4th Dimension has 4 elements each
'''
   [ 1  2  3  4]
'''

# Slicing
arr[2 , 0, 2, 1:3]

array([28, 29])

In [262]:
arr.shape

(3, 1, 3, 4)

# Reshape

In [344]:
re_arr = arr
re_arr = re_arr.reshape(6, 6)
print(re_arr)

[[ 1  2  3  4  4  5]
 [ 6  7  7  8  9  0]
 [11 12 13 14 14 15]
 [16 17 17 18 19 10]
 [21 22 23 24 24 25]
 [26 27 27 28 29 20]]


# Flatern Matrix

In [359]:
# Creates a 1D vector of the matrix
fl_arr = re_arr
fl_arr = fl_arr.ravel()
print(fl_arr)

[ 1  2  3  4  4  5  6  7  7  8  9  0 11 12 13 14 14 15 16 17 17 18 19 10
 21 22 23 24 24 25 26 27 27 28 29 20]


# Creating a grey image

In [25]:
image = np.zeros((250,510))
image.shape

(250, 510)

In [11]:
image[:,:] = 100
# image = image[:,:] + 10
# OR
# image[:,:] =110

# Creating White rectangels in the grey image
# height = image.max()
# image[int(image.shape[0]/2) - 25 :int(image.shape[0]/2) + 26, int(image.shape[1]/2) - 25 :int(image.shape[1]/2)+26] = 255

In [398]:
cv2.imwrite('sample.jpg', image)

True

In [17]:
print(image.shape[1])

200


In [27]:
color = 0
# Row Gradient
for i in range(image.shape[1]):
    image[i,:] = i* (255/image.shape[1])

#Column Gradient
color = 0
for i in range(image.shape[1]):
    color_value = int(i * (255 / (image.shape[1] - 1)))
    image[:, i] = color_value

In [29]:
print(image)

[[  0.   0.   1. ... 253. 254. 255.]
 [  0.   0.   1. ... 253. 254. 255.]
 [  0.   0.   1. ... 253. 254. 255.]
 ...
 [  0.   0.   1. ... 253. 254. 255.]
 [  0.   0.   1. ... 253. 254. 255.]
 [  0.   0.   1. ... 253. 254. 255.]]


In [31]:
cv2.imwrite('gradient.jpg', image)

True

In [147]:
f = [1,2,3,4,5,6,7]
for i in enumerate(f):
    print(i)

(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)
(6, 7)
