In [1]:
import cv2
import numpy as np

# Reversing a Video

In [3]:
#initializing video reader
cap = cv2.VideoCapture('../Yolo_projects/Videos/car_count.mp4')

#getting video information
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
fps = int(cap.get(cv2.CAP_PROP_FPS))
frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
res = kheight)

# initializing video writter
fourcc = cv2.VideoWriter_fourcc(*'MP4V') # initializing the codec
out = cv2.VideoWriter('rev.mp4', fourcc, fps, res)

In [4]:
print(height, width, fps, frames)

768 1366 50 3002


In [5]:
last_frame = frames - 1
rotation_increment = 360/frames
frame_count = 0

In [8]:
while last_frame>=0:
    #setting the video start to last frame
    cap.set(cv2.CAP_PROP_POS_FRAMES, last_frame)
    #readign the video
    success, img = cap.read()
    if success:
        # Video Rotation Logic
        rotation_angle = (frames - last_frame) * rotation_increment
        # Rotation Matrix
        rotation_matrix = cv2.getRotationMatrix2D((width/2, height/2), rotation_angle, 1)
        # Adding Rotation to the video
        rotated = cv2.warpAffine(img, rotation_matrix, (width, height))
    
        # To show the video in window
        # cv2.imshow("image", img)
        # if cv2.waitKey(1) & 0xFF == ord('q'):
        #     break
    
        # Writting the reversed video
        out.write(rotated)

        frame_count += 1

        # Print progress every 100 frames
        if frame_count % 100 == 0:
            print(f'Frames written: {frame_count}/{frames} ({(frame_count / frames) * 100:.2f}%)')
    
        # moving the last_frame counter by 1
        last_frame = last_frame - 1
    

# Release the video capture and close any OpenCV windows
cap.release()
out.release()
cv2.destroyAllWindows()

Frames written: 100/3002 (3.33%)
Frames written: 200/3002 (6.66%)
Frames written: 300/3002 (9.99%)
Frames written: 400/3002 (13.32%)
Frames written: 500/3002 (16.66%)
Frames written: 600/3002 (19.99%)
Frames written: 700/3002 (23.32%)
Frames written: 800/3002 (26.65%)
Frames written: 900/3002 (29.98%)
Frames written: 1000/3002 (33.31%)
Frames written: 1100/3002 (36.64%)
Frames written: 1200/3002 (39.97%)
Frames written: 1300/3002 (43.30%)
Frames written: 1400/3002 (46.64%)
Frames written: 1500/3002 (49.97%)
Frames written: 1600/3002 (53.30%)
Frames written: 1700/3002 (56.63%)
Frames written: 1800/3002 (59.96%)
Frames written: 1900/3002 (63.29%)
Frames written: 2000/3002 (66.62%)
Frames written: 2100/3002 (69.95%)
Frames written: 2200/3002 (73.28%)
Frames written: 2300/3002 (76.62%)
Frames written: 2400/3002 (79.95%)
Frames written: 2500/3002 (83.28%)
Frames written: 2600/3002 (86.61%)
Frames written: 2700/3002 (89.94%)
Frames written: 2800/3002 (93.27%)
Frames written: 2900/3002 (96.60

# Drawing Coloured Lines, Shapes and Texts

In [255]:
canvas = np.zeros((500,500, 3)) # 3 for RGB channel

## Creating Lines(aliasing - LN_4, LN_8 & anti aliasing - LN_AA)

In [257]:
# Line 4 & 8 - bresenham
cv2.line(canvas, (25,25), (475, 25), (255,255,255), 3, cv2.LINE_4)
# Line AA - Gaussian Filtering
cv2.line(canvas, (25,325), (475, 325), (255,255,255), 3, cv2.LINE_AA)

# cv2.imshow('image', canvas)
# cv2.waitKey(0)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Creating Rectangle

In [259]:
cv2.rectangle(canvas, (120,40), (195, 310), (120,150,0), 1, cv2.LINE_4) #thickness = -1 for filled rectangle
# cv2.imshow('image', canvas)
# cv2.waitKey(0)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Creating Arrow Line

In [261]:
cv2.arrowedLine(canvas, (215,175), (235, 175), (255,255,255), 2, cv2.LINE_AA, tipLength = .2)
# cv2.imshow('image', canvas)
# cv2.waitKey(0)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Creating Circles

In [263]:
cv2.circle(canvas, (330,175), 75, (120,0,120), -1, cv2.LINE_8) #thickness = -1 for filled rectangle
canvas[175, 237] = 255
cv2.imshow('image', canvas)
cv2.waitKey(0)

-1

# Drawing PolyLines

In [291]:
canvas = np.zeros((300,300,3))

In [295]:
# Point to plot on canvas
pts = np.array([[10,5], [30, 25], [50, 5], [30, 50]], np.int32)

#reshaping points to shape (number_vertex, 1, 2)
pts = pts.reshape(-1,1,2)

# Drawing Polygon
cv2.polylines(canvas, [pts], True, (255,255,255)) # Here Boolean(True, False) determines if figure is closed(True) or not(False)

cv2.imshow('Image', canvas)
cv2.waitKey(0)

error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\drawing.cpp:2059: error: (-215:Assertion failed) pts && npts && ncontours >= 0 && 0 <= thickness && thickness <= MAX_THICKNESS && 0 <= shift && shift <= XY_SHIFT in function 'cv::polylines'


# Writting on Image

In [366]:
canvas = np.zeros([600,500])

In [362]:
fonts = [cv2.FONT_HERSHEY_COMPLEX,
        cv2.FONT_HERSHEY_COMPLEX_SMALL,
        cv2.FONT_HERSHEY_DUPLEX,
        cv2.FONT_HERSHEY_PLAIN,
        cv2.FONT_HERSHEY_SCRIPT_COMPLEX,
        cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,
        cv2.FONT_HERSHEY_SIMPLEX,
        cv2.FONT_HERSHEY_TRIPLEX]

In [370]:
pos = np.array([10,25])
for i in range(0, len(fonts)):
    print()
    cv2.putText(canvas, "I'M Shubham".upper(), pos, fonts[i], 1, (255, 255,255), 2)
    pos = [pos[0], pos[1]+35]
    cv2.putText(canvas, "I'M Shubham".lower(), pos, fonts[i], 1, (255), 2)
    pos = [pos[0] , pos[1]+35]

cv2.imshow("image", canvas)
cv2.waitKey(0)

-1